import { Open_Sans, Playfair_Display } from "next/font/google";
import "./globals.css";
import LayoutWrapper from "@/components/Common/LayoutWrapper";
import Providers from "./provider";
import { Toaster } from "react-hot-toast";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-playfair",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${openSans.variable} ${playfair.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <LayoutWrapper>
  <Providers>
          {children}
          <Toaster position="top-right" />
          </Providers>
        </LayoutWrapper>
      </body>
    </html>
  );
}